version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/weva
      - JWT_SECRET=change_me
      - CORS_ORIGINS=http://localhost:5173
      - STUB_MODE=true
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  mongo-data:


